### PR TITLE
Add missing <R_ext/Rdynload.h> include for R_GetCCallable.

### PR DESCRIPTION
**Pull request by kiwiwarmnfuzzy**
This should resolve https://github.com/eddelbuettel/rcppcctz/issues/41.

### CODE REVIEW

**Review by eddelbuettel — COMMENTED** [review]
It would be nice if you could add a ChangeLog entry in the standard format (date, two spaces, name, two spaces, email).  I see your work email is attached to the patch, feel free to use another  (but it would be nice if it was a working and valid one).

**Comment by eddelbuettel** [comment]
And as discussed in #41 it may actually make sense to also relace R.h with just what is needed.

**Comment by kiwiwarmnfuzzy** [comment]
Thanks for the suggestions! Updated according to previous comment; please take another look, thanks!

**Comment by eddelbuettel** [comment]
Nice, thank you. [1] Is `cstdint` really all it needs?  I presume you called 'include what you use' on it?  I have a shell script somewhere to invoke that but ... I am currently on vacation :) so a little further from my machine.

Now that I have you here ... do you by chance follow CCTZ upstream too?  There hasn't been a release but I should probably refresh the headers and thereby get update TZ info for free...

[1] It'll need minor whitespace fix on the first line and re-indenting the main line but I'll take of that when I wrap up a next release. Thanks for adding the entry!

**Comment by eddelbuettel** [comment]
Thanks again. Now merged, and added a minor edit on ChangeLog (had the wrong file referenced too), added NEWS and rolled version.  I will maybe try to update the headers and then see about shipping a new version.

**Comment by eddelbuettel** [comment]
Thanks again.  Now that CRAN has reopened after their summer break I just shipped a new version 0.2.11 which also has minimally updated headers relative to upstream.

**Pull request merged**
